name: base
channels:
  - conda-forge
  - defaults
dependencies:
  - _ipyw_jlab_nb_ext_conf=0.1.0
  - alabaster=0.7.12
  - anaconda=2020.11
  - anaconda-client=1.7.2
  - anaconda-navigator=1.10.0
  - anaconda-project=0.8.4
  - argh=0.26.2
  - argon2-cffi=20.1.0
  - arviz=0.10.0
  - asn1crypto=1.4.0
  - astroid=2.4.2
  - astropy=4.0.2
  - async_generator=1.10
  - atomicwrites=1.4.0
  - attrs=20.3.0
  - autopep8=1.5.4
  - babel=2.8.1
  - backcall=0.2.0
  - backports=1.0
  - backports.functools_lru_cache=1.6.1
  - backports.shutil_get_terminal_size=1.0.0
  - backports.tempfile=1.0
  - backports.weakref=1.0.post1
  - bcrypt=3.2.0
  - beautifulsoup4=4.9.3
  - bitarray=1.6.1
  - bkcharts=0.2
  - blas=1.0
  - bleach=3.2.1
  - blosc=1.20.1
  - boto=2.49.0
  - bottleneck=1.3.2
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - ca-certificates=2020.10.14
  - certifi=2020.6.20
  - cffi=1.14.3
  - cftime=1.3.0
  - chardet=3.0.4
  - click=7.1.2
  - cloudpickle=1.6.0
  - clyent=1.2.2
  - colorama=0.4.4
  - comtypes=1.1.7
  - conda=4.9.2
  - conda-build=3.20.5
  - conda-env=2.6.0
  - conda-package-handling=1.7.2
  - conda-verify=3.4.2
  - console_shortcut=0.1.1
  - contextlib2=0.6.0.post1
  - cryptography=3.1.1
  - curl=7.71.1
  - cvxpy=1.1.7
  - cvxpy-base=1.1.7
  - cycler=0.10.0
  - cython=0.29.21
  - cytoolz=0.11.0
  - dask=2.30.0
  - dask-core=2.30.0
  - decorator=4.4.2
  - defusedxml=0.6.0
  - diff-match-patch=20200713
  - distributed=2.30.1
  - docutils=0.16
  - ecos=2.0.7.post1
  - entrypoints=0.3
  - et_xmlfile=1.0.1
  - fastcache=1.1.0
  - filelock=3.0.12
  - flake8=3.8.4
  - flask=1.1.2
  - freetype=2.10.4
  - fsspec=0.8.3
  - future=0.18.2
  - get_terminal_size=1.0.0
  - gevent=20.9.0
  - glob2=0.7
  - graphviz=2.38.0
  - greenlet=0.4.17
  - h5py=2.10.0
  - hdf4=4.2.13
  - hdf5=1.10.4
  - heapdict=1.0.1
  - html5lib=1.1
  - icc_rt=2019.0.0
  - icu=58.2
  - idna=2.10
  - imageio=2.9.0
  - imagesize=1.2.0
  - importlib-metadata=2.0.0
  - importlib_metadata=2.0.0
  - iniconfig=1.1.1
  - intel-openmp=2020.2
  - intervaltree=3.1.0
  - ipython=7.19.0
  - ipython_genutils=0.2.0
  - ipywidgets=7.5.1
  - isort=5.6.4
  - itsdangerous=1.1.0
  - jdcal=1.4.1
  - jedi=0.17.1
  - jinja2=2.11.2
  - joblib=0.17.0
  - jpeg=9b
  - json5=0.9.5
  - jsonschema=3.2.0
  - jupyter=1.0.0
  - jupyter_client=6.1.7
  - jupyter_console=6.2.0
  - jupyter_core=4.6.3
  - jupyterlab=2.2.6
  - jupyterlab_pygments=0.1.2
  - jupyterlab_server=1.2.0
  - keyring=21.4.0
  - kiwisolver=1.3.0
  - krb5=1.18.2
  - lazy-object-proxy=1.4.3
  - libarchive=3.4.2
  - libblas=3.8.0
  - libcurl=7.71.1
  - libgpuarray=0.7.6
  - libiconv=1.15
  - liblapack=3.8.0
  - liblief=0.10.1
  - libnetcdf=4.7.3
  - libpng=1.6.37
  - libpython=2.1
  - libsodium=1.0.18
  - libspatialindex=1.9.3
  - libssh2=1.9.0
  - libtiff=4.1.0
  - libxml2=2.9.10
  - libxslt=1.1.34
  - llvmlite=0.34.0
  - locket=0.2.0
  - lxml=4.6.1
  - lz4-c=1.9.2
  - lzo=2.10
  - m2w64-binutils=2.25.1
  - m2w64-bzip2=1.0.6
  - m2w64-crt-git=5.0.0.4636.2595836
  - m2w64-gcc=5.3.0
  - m2w64-gcc-ada=5.3.0
  - m2w64-gcc-fortran=5.3.0
  - m2w64-gcc-libgfortran=5.3.0
  - m2w64-gcc-libs=5.3.0
  - m2w64-gcc-libs-core=5.3.0
  - m2w64-gcc-objc=5.3.0
  - m2w64-gmp=6.1.0
  - m2w64-headers-git=5.0.0.4636.c0ad18a
  - m2w64-isl=0.16.1
  - m2w64-libiconv=1.14
  - m2w64-libmangle-git=5.0.0.4509.2e5a9a2
  - m2w64-libwinpthread-git=5.0.0.4634.697f757
  - m2w64-make=4.1.2351.a80a8b8
  - m2w64-mpc=1.0.3
  - m2w64-mpfr=3.1.4
  - m2w64-pkg-config=0.29.1
  - m2w64-toolchain=5.3.0
  - m2w64-tools-git=5.0.0.4592.90b8472
  - m2w64-windows-default-manifest=6.4
  - m2w64-winpthreads-git=5.0.0.4634.697f757
  - m2w64-zlib=1.2.8
  - mako=1.1.3
  - markupsafe=1.1.1
  - mccabe=0.6.1
  - menuinst=1.4.16
  - mistune=0.8.4
  - mkl=2020.2
  - mkl-service=2.3.0
  - mkl_fft=1.2.0
  - mkl_random=1.1.1
  - mock=4.0.2
  - more-itertools=8.6.0
  - mpmath=1.1.0
  - msgpack-python=1.0.0
  - msys2-conda-epoch=20160418
  - multipledispatch=0.6.0
  - navigator-updater=0.2.1
  - nbclient=0.5.1
  - nbconvert=6.0.7
  - nbformat=5.0.8
  - nest-asyncio=1.4.2
  - netcdf4=1.5.3
  - networkx=2.5
  - nltk=3.5
  - nose=1.3.7
  - notebook=6.1.4
  - numba=0.51.2
  - numexpr=2.7.1
  - numpydoc=1.1.0
  - olefile=0.46
  - openpyxl=3.0.5
  - openssl=1.1.1h
  - osqp=0.6.1
  - packaging=20.4
  - pandas=1.1.3
  - pandoc=2.11
  - pandocfilters=1.4.3
  - paramiko=2.7.2
  - parso=0.7.0
  - partd=1.1.0
  - path=15.0.0
  - path.py=12.5.0
  - pathlib2=2.3.5
  - pathtools=0.1.2
  - patsy=0.5.1
  - pep8=1.7.1
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=8.0.1
  - pip=20.2.4
  - pkginfo=1.6.1
  - pluggy=0.13.1
  - ply=3.11
  - powershell_shortcut=0.0.1
  - prometheus_client=0.8.0
  - prompt-toolkit=3.0.8
  - prompt_toolkit=3.0.8
  - psutil=5.7.2
  - py=1.9.0
  - py-lief=0.10.1
  - pycodestyle=2.6.0
  - pycosat=0.6.3
  - pycparser=2.20
  - pycurl=7.43.0.6
  - pydocstyle=5.1.1
  - pyflakes=2.2.0
  - pygments=2.7.2
  - pygpu=0.7.6
  - pylint=2.6.0
  - pymc3=3.8
  - pynacl=1.4.0
  - pyodbc=4.0.30
  - pyopenssl=19.1.0
  - pyparsing=2.4.7
  - pyqt=5.9.2
  - pyreadline=2.1
  - pyrsistent=0.17.3
  - pysocks=1.7.1
  - pytables=3.6.1
  - python=3.8.5
  - python-dateutil=2.8.1
  - python-graphviz=0.15
  - python-jsonrpc-server=0.4.0
  - python-language-server=0.35.1
  - python-libarchive-c=2.9
  - python_abi=3.8
  - pytz=2020.1
  - pywavelets=1.1.1
  - pywin32=227
  - pywin32-ctypes=0.2.0
  - pywinpty=0.5.7
  - pyyaml=5.3.1
  - pyzmq=19.0.2
  - qdarkstyle=2.8.1
  - qt=5.9.7
  - qtawesome=1.0.1
  - qtconsole=4.7.7
  - qtpy=1.9.0
  - regex=2020.10.15
  - requests=2.24.0
  - rope=0.18.0
  - rtree=0.9.4
  - ruamel_yaml=0.15.87
  - scikit-image=0.17.2
  - scikit-learn=0.23.2
  - scipy=1.5.2
  - scs=2.1.2
  - seaborn=0.11.0
  - send2trash=1.5.0
  - setuptools=50.3.1
  - simplegeneric=0.8.1
  - singledispatch=3.4.0.3
  - sip=4.19.13
  - six=1.15.0
  - snowballstemmer=2.0.0
  - sortedcollections=1.2.1
  - sortedcontainers=2.2.2
  - soupsieve=2.0.1
  - sphinx=3.2.1
  - sphinxcontrib=1.0
  - sphinxcontrib-applehelp=1.0.2
  - sphinxcontrib-devhelp=1.0.2
  - sphinxcontrib-htmlhelp=1.0.3
  - sphinxcontrib-jsmath=1.0.1
  - sphinxcontrib-qthelp=1.0.3
  - sphinxcontrib-serializinghtml=1.1.4
  - sphinxcontrib-websupport=1.2.4
  - spyder=4.1.5
  - spyder-kernels=1.9.4
  - sqlalchemy=1.3.20
  - sqlite=3.33.0
  - statsmodels=0.12.0
  - sympy=1.6.2
  - tblib=1.7.0
  - terminado=0.9.1
  - testpath=0.4.4
  - theano=1.0.5
  - threadpoolctl=2.1.0
  - tifffile=2020.10.1
  - tk=8.6.10
  - toml=0.10.1
  - toolz=0.11.1
  - tornado=6.0.4
  - tqdm=4.50.2
  - traitlets=5.0.5
  - typing_extensions=3.7.4.3
  - ujson=4.0.1
  - unicodecsv=0.14.1
  - urllib3=1.25.11
  - vc=14.1
  - vs2015_runtime=14.16.27012
  - vs2017_win-64=19.16.27038
  - vswhere=2.7.1
  - watchdog=0.10.3
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - werkzeug=1.0.1
  - wheel=0.35.1
  - widgetsnbextension=3.5.1
  - win_inet_pton=1.1.0
  - win_unicode_console=0.5
  - wincertstore=0.2
  - winpty=0.4.3
  - wrapt=1.11.2
  - xarray=0.16.2
  - xlrd=1.2.0
  - xlsxwriter=1.3.7
  - xlwings=0.20.8
  - xlwt=1.3.0
  - xmltodict=0.12.0
  - xz=5.2.5
  - yaml=0.2.5
  - yapf=0.30.0
  - zeromq=4.3.2
  - zict=2.0.0
  - zipp=3.4.0
  - zlib=1.2.11
  - zope=1.0
  - zope.event=4.5.0
  - zope.interface=5.1.2
  - zstd=1.4.5
  - pip:
    - aiohttp==3.7.3
    - alpha-vantage==2.3.1
    - async-timeout==3.0.1
    - auquan-toolbox==2.1.92
    - backtrader==1.9.76.123
    - backtrader-plotting==1.1.0
    - bokeh==2.0.2
    - bs4==0.0.1
    - cvxopt==1.2.5.post1
    - empyrical==0.5.5
    - gym==0.17.3
    - helpdev==0.7.1
    - ibapi==9.81.1.post1
    - investpy==1.0
    - ipykernel==5.4.2
    - keras==2.4.3
    - markdown2==2.3.10
    - matplotlib==3.2.2
    - multidict==5.1.0
    - multitasking==0.0.9
    - nsepy==0.8
    - numpy==1.18.5
    - pandas-datareader==0.9.0
    - plotly==4.14.1
    - pyfolio==0.9.2
    - pyglet==1.5.0
    - pyportfolioopt==1.2.7
    - pyqt5==5.15.2
    - pyqt5-sip==12.8.1
    - pytest==6.2.0
    - quanttrader==0.5.2
    - retrying==1.3.3
    - sklearn==0.0
    - ta-lib==0.4.19
    - tensorboardx==2.1
    - unidecode==1.1.1
    - yahoo-fin==0.8.6
    - yarl==1.6.3
    - yfinance==0.1.55
prefix: C:\ProgramData\Anaconda3
